name: Build blog docker image
on:
    push:
        branches:
            - master
jobs:
    Build-Blog-Image:
        runs-on: archlinux
        steps:
            -   uses: https://mirrors.rrricardo.top/actions/checkout.git@v4
                name: Check out code
                with:
                    lfs: true
            -   name: Build project
                run: |
                    cd YaeBlog
                    dotnet publish
            -   name: Build docker image
                run: |
                    cd YaeBlog
                    podman build . -t registry.cn-beijing.aliyuncs.com/jackfiled/blog:latest
            -   name: Login aliyun docker registry
                uses: https://mirrors.rrricardo.top/actions/podman-login.git@v1
                with:
                    registry: registry.cn-beijing.aliyuncs.com
                    username: 初冬的朝阳
                    password: ${{ secrets.ALIYUN_PASSWORD }}
                    auth_file_path: /etc/containers/auth.json
            -   name: Push docker image
                run: podman push registry.cn-beijing.aliyuncs.com/jackfiled/blog:latest
