name: Build blog docker image
on:
  push:
    branches:
      - master
jobs:
  Build-Blog-Image:
    runs-on: archlinux
    steps:
      - name: Check out code.
        uses: https://mirrors.rrricardo.top/actions/checkout.git@v4
        with:
          lfs: true
      - name: Build project.
        run: |
          proxy
          podman pull mcr.microsoft.com/dotnet/aspnet:10.0
          unproxy
          cd YaeBlog
          pwsh build.ps1 build
      - name: Workaround to make sure podman-login working.
        run: |
          mkdir /root/.docker
      - name: Login tencent cloud docker registry.
        uses: https://mirrors.rrricardo.top/actions/podman-login.git@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: 100044380877
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}
          auth_file_path: /etc/containers/auth.json
      - name: Push docker image.
        run: podman push ccr.ccs.tencentyun.com/jackfiled/blog:latest
